COLOR_OFF = 0
COLOR_WHITE = 3
COLOR_RED = 5
COLOR_GREEN = 21
COLOR_BLUE = 79
COLOR_ORANGE = 9
COLOR_PURPLE = 49

COLORS = [
    COLOR_WHITE,
    COLOR_RED,
    COLOR_GREEN,
    COLOR_BLUE,
    COLOR_ORANGE,
    COLOR_PURPLE
]