CONTROL_PAD_UP = 104
CONTROL_PAD_DOWN = 105
CONTROL_PAD_BACK = 106
CONTROL_PAD_FORWARD = 107
CONTROL_PAD_SESSION = 108
CONTROL_PAD_USER1 = 109
CONTROL_PAD_USER2 = 110
CONTROL_PAD_MIXER = 111

CONTROL_PAD_RECORD_ARM = 19
CONTROL_PAD_SOLO = 29
CONTROL_PAD_MUTE = 39
CONTROL_PAD_STOP = 49
CONTROL_PAD_SEND_B = 59
CONTROL_PAD_SEND_A = 69
CONTROL_PAD_PAN = 79
CONTROL_PAD_VOLUME = 89

CONTROL_PADS = [
    CONTROL_PAD_UP,
    CONTROL_PAD_DOWN,
    CONTROL_PAD_BACK,
    CONTROL_PAD_FORWARD,
    CONTROL_PAD_SESSION,
    CONTROL_PAD_USER1,
    CONTROL_PAD_USER2,
    CONTROL_PAD_MIXER,

    CONTROL_PAD_RECORD_ARM,
    CONTROL_PAD_SOLO,
    CONTROL_PAD_MUTE,
    CONTROL_PAD_STOP,
    CONTROL_PAD_SEND_B,
    CONTROL_PAD_SEND_A,
    CONTROL_PAD_PAN,
    CONTROL_PAD_VOLUME,
]

ALT_STATUS_PADS = [
    CONTROL_PAD_UP,
    CONTROL_PAD_DOWN,
    CONTROL_PAD_BACK,
    CONTROL_PAD_FORWARD,
    CONTROL_PAD_SESSION,
    CONTROL_PAD_USER1,
    CONTROL_PAD_USER2,
    CONTROL_PAD_MIXER,
]